### ISSUE TITLE
KIA EV6 환경 에서 CLU15 를 지원하지 않습니다. 

### ISSUE THREAD

**Issue by KongYoulBaek** [crwusiz/openpilot#13]
https://github.com/crwusiz/openpilot/blob/b6969d12885fc3871bce7e7a7c7df4997b605e3c/selfdrive/car/hyundai/carstate.py#L267

- KIA EV6 2022 차종은 hyundai_canfd.dbc 을 사용합니다.
해당 dbc에서 CLU15 항목이 없습니다.

**Comment by crwusiz** [comment]
삭제했습니다
