### ISSUE TITLE
carcontroller.py, update_canfd 에서  CC.hudControl 누락 

### ISSUE THREAD

**Issue by KongYoulBaek** [crwusiz/openpilot#15]
https://github.com/crwusiz/openpilot/blob/b6969d12885fc3871bce7e7a7c7df4997b605e3c/selfdrive/car/hyundai/carcontroller.py#L238

hud_control = CC.hudControl

누락된 것으로 보입니다.

**Comment by crwusiz** [comment]
추가했습니다
