### ISSUE TITLE
Openpilot unavailable

### ISSUE THREAD

**Issue by chanhojung** [crwusiz/openpilot#25]
Elect gear 관련 문제로 인게이지가 안되네요
![20230930_112913](https://github.com/crwusiz/openpilot/assets/29187928/b99bc133-2504-47c2-a09a-077d9eec64cb)

**Comment by chanhojung** [comment]
Grandeur IGFL hev 입니다
콤마순정 및 다른  브랜치(opkr apilot)에선 잘됩니다

**Comment by crwusiz** [comment]
오류확인 감사합니다
