### ISSUE TITLE
Harness Type  오기 검토 요청

### ISSUE THREAD

**Issue by chanhojung** [crwusiz/openpilot#33]
기존 그랜저(K)에서 Genesis GV70으로 하나 구입하려고 하는데 cruwsiz 님 페이지에 보면 동일한 K형으로 되어 
굳이 하네스 케이블 새로 구매할 필요 없다고 생각했는데
comma.ai에 들어가보니 아래와 같이 cruwsiz 님 설명자료와 완전이 다르네요
그것도 년식별로 모두 타입이 다른 것 같은데 TT

Genesis G70 2018 Harness: Hyundai F
Genesis G70 2019-21 Harness: Hyundai F
Genesis G70 2022-23 Harness: Hyundai L
Genesis G80 2017 Harness: Hyundai J
Genesis G80 2018-19 Harness: Hyundai H
Genesis G80 (2.5T Advanced Trim, with HDA II) 2024 Harness: Hyundai P
Genesis G90 2017-20 Harness: Hyundai C
Genesis GV60 (Advanced Trim) 2023 Harness: Hyundai A
Genesis GV60 (Performance Trim) 2022-23 Harness: Hyundai K
Genesis GV70 (2.5T Trim, without HDA II) 2022-23 Harness: Hyundai L
Genesis GV70 (3.5T Trim, without HDA II) 2022-23 Harness: Hyundai M
Genesis GV70 Electrified (with HDA II) 2023 Harness: Hyundai Q
Genesis GV80 2023 Harness: Hyundai M

**Comment by crwusiz** [comment]
A K L M 은 공용으로 사용하고
차량옵션별로 다르기때문에 참고만 하시면 됩니다.
비교표는 GSW 연식 기준으로 만들어놓은것 입니다.

**Comment by ChanHoya** [comment]
그러면 젠더 모양이 약간 다른것은 안맞을 경우 깎거나 잘라서 맞추면 되나요.

**Comment by crwusiz** [comment]
네.. 맞습니다.

**Comment by ChanHoya** [comment]
제가 기존 그랜저 IG(type K)를 사용하고 있었고
GV70 받기 전에 임시로 그랜저 GN7받았는데 K 가 아니라 A이네요
그래서 말씀처럼 A K 도 호환을 보여서 깎아서 해보려는데 외부에 노출된 양각은 깎기 쉽지만 안에 들어간 부분을 깎아내는게 쉽지 않네요
현기차는 왜 이리 소켓을 비호횐으로 만들었을까요 
쒯~ ^^
