### ISSUE TITLE
0810 프로세스 가 응답하지 않아요 = 에러메세지

### ISSUE THREAD

**Issue by ktaejung01** [crwusiz/openpilot#7]
차종 = 캠리 하브 2021
버젼 = 0810

설명 
089 까지는 자동설치후 핑거만 수정하믄 잘됐습죠
0810은 깃허브에서 클론한뒤 체크아웃-핑거만 수정
하믄 다음 메세지 나와용

![IMG_1618](https://user-images.githubusercontent.com/83075594/142748769-7485a098-5dfe-4618-b163-fcf4ffd73484.jpg)

**Comment by crwusiz** [comment]
노트북 이용해서 ssh 접속 하셔서 tmux a
해보시면 프로세스중 중지된 프로세스는 빨간색으로 표시됩니다..

그 사진이 필요하고..
중지된 프로세스의 종료 원인을 파악하려면 그 프로세스만 따로 실행해보면 확인이 더 쉽습니다.

**Comment by ktaejung01** [comment]
> 노트북 이용해서 ssh 접속 하셔서 tmux a 해보시면 프로세스중 중지된 프로세스는 빨간색으로 표시됩니다..
> 
> 그 사진이 필요하고.. 중지된 프로세스의 종료 원인을 파악하려면 그 프로세스만 따로 실행해보면 확인이 더 쉽습니다.

==================

tmux a 돌렸음다

controld 가 에러 나옵니다

====

selfdrive/boardd/panda.cc: lost connection
camerad clocksd dmonitoringmodeld logcatd loggerd modeld proclogd sensord ubloxd ui soundd locationd calibrationd controlsd deleter dmonitoringd logmessaged pandad paramsd plannerd radard thermald tombstoned rtshield androidd
camerad clocksd dmonitoringmodeld logcatd loggerd modeld proclogd sensord ubloxd ui soundd locationd calibrationd controlsd deleter dmonitoringd logmessaged pandad paramsd plannerd radard thermald tombstoned rtshield androidd
selfdrive/ui/qt/onroad.cc: slow frame time: 96.73

=============
<img width="937" alt="0810error_001" src="https://user-images.githubusercontent.com/83075594/143157839-3152bd22-1853-40f2-ae30-250390e675c6.PNG">

**Comment by ktaejung01** [comment]
089 버젼에 도요타 하브 한국향 핑거프린트 추가 요청드려용!!

캠리 까페에서 핑거작업 문의 자주 들어와요

{   
36: 8, 37: 8, 166: 8, 170: 8, 180: 8, 295: 8, 296: 8, 426: 6, 452: 8, 466: 8, 467: 8, 550: 8, 552: 4, 560: 7, 562: 6, 581: 5, 608: 8, 610: 8, 643: 7, 713: 8, 728: 8, 740: 5, 761: 8, 764: 8, 800: 8, 810: 2, 812: 8, 818: 8, 824: 8, 829: 2, 830: 7, 835: 8, 836: 8, 865: 8, 869: 7, 870: 7, 871: 2, 888: 8, 889: 8, 896: 8, 898: 8, 900: 6, 902: 6, 905: 8, 913: 8, 918: 8, 921: 8, 933: 8, 934: 8, 935: 8, 944: 8, 945: 8, 950: 8, 951: 8, 953: 8, 955: 8, 956: 8, 971: 7, 975: 5, 993: 8, 998: 5, 999: 7, 1000: 8, 1001: 8, 1002: 8, 1017: 8, 1020: 8, 1041: 8, 1042: 8, 1044: 8, 1056: 8, 1057: 8, 1059: 1, 1071: 8, 1076: 8, 1077: 8, 1114: 8, 1161: 8, 1162: 8, 1163: 8, 1164: 8, 1165: 8, 1166: 8, 1167: 8, 1228: 8, 1235: 8, 1264: 8, 1279: 8, 1541: 8, 1552: 8, 1553: 8, 1556: 8, 1557: 8, 1568: 8, 1570: 8, 1571: 8, 1572: 8, 1592: 8, 1593: 8, 1594: 8, 1595: 8, 1745: 8, 1779: 8, 1786: 8, 1787: 8, 1788: 8, 1789: 8, 1904: 8, 1912: 8, 1990: 8, 1998: 8 
 },
